# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV1@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/terraform'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'StorageAccount-Terraform'
    backendServiceArm: 'Terraform-saw'
    backendAzureRmResourceGroupName: 'sowmithri-rg'
    backendAzureRmStorageAccountName: 'storemfwttwheqnyuk'
    backendAzureRmContainerName: 'testcontainer1'
    backendAzureRmKey: 'tf/terraform.tfstate'
  

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'StorageAccount-Terraform'
    environmentServiceNameAzureRM: 'Terraform-saw'
